issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/pprof-format:environment:npm

claim_pattern:
  event_name: push
  job_workflow_ref: DataDog/pprof-format/\.github/workflows/release\.yml@refs/heads/v[0-9]+\.x
  ref: refs/heads/v[0-9]+\.x
  repository: DataDog/pprof-format

permissions:
  contents: write
