name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24, 26]
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 18
    - run: npm ci
    - run: npm run lint
